[build]
  publish = "public/"
  functions = "functions/"

# Specific service routes BEFORE the general API catch-all
[[redirects]]
  from = "/api/transaction-service/*"
  to = "/.netlify/functions/transaction-service"
  status = 200
  force = true

[[redirects]]
  from = "/api/account-service/*"
  to = "/.netlify/functions/account-service/account-service"
  status = 200
  force = true # Make sure this rule is processed first

# General API catch-all rule (example)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 